### ISSUE TITLE
Drawing tools fix for TV charts 

### ISSUE THREAD

**Issue by rocket-pig** [nirvanatikku/bittrex-enhanced#12]
Increasing chart height to 500 in settings makes the drawing tools bar show up on left side. Maybe set this by default?

**Comment by nirvanatikku** [comment]
I used to have it at 500px, but then I got feedback that it made sense to default the size to the original chart's dimensions. Perhaps the better way to do this is to offer this as part of the settings vs defaults.. thoughts?

**Comment by rocket-pig** [comment]
Could, yes. You mean make a checkbox "Show drawing tools"? I like this idea.
