### ISSUE TITLE
Setting to make USD and BTC value closer like before?

### ISSUE THREAD

**Issue by ssithuxz** [nirvanatikku/bittrex-enhanced#18]
Personally, I do not like how EST USD has his own column. The way it was before made it easier on my eyes.

Thanks

**Comment by nirvanatikku** [comment]
Thx for the feedback. Does this apply universally or to the market specific page? meaning, would you be ok with additional columns in balance and markets tables; just want it to be inline on the market page?

**Comment by ssithuxz** [comment]
hmm i think im just nitpicking.. after 1 day of this, its not bad at all.. ill close this issue
