### ISSUE TITLE
Convert order book BTC to USD?

### ISSUE THREAD

**Issue by ssithuxz** [nirvanatikku/bittrex-enhanced#19]
https://i.imgur.com/KT5o87e.png

Just thought it'd be nice if you could make the actual rate / cost/proceeds convert from BTC to USD.

That way I can easily figure out how much I made on a trade.

Thanks !

**Comment by nirvanatikku** [comment]
Unfortunately I haven't found an easy way to gather the price of BTC at that given time.. which would more accurately reflect the transactions. Do you think there's value in adding a conversion to the current BTC value? It could be a bit misleading.. lmk

**Comment by ssithuxz** [comment]
Why is this different from adding current btc to usd value for home page and elsewhere?

**Comment by nirvanatikku** [comment]
In this instance, the price of BTC at the time you executed needs to be taken into account? If I were to use the current BTC price, that would only show what the proceeds _would_ be at that moment. 

Am I missing something?

**Comment by ssithuxz** [comment]
Yes whenever I open that page, I want to know what my gains were even though BTC is constantly changing in price. My gains would be different everytime I open the page but it still would be nice to see the difference. Right now, i have to constantly add and subtract my buys and sells and convert the btc to usd with google to see what my profit was.

"If I were to use the current BTC price, that would only show what the proceeds would be at that moment" -> I would like that to be implemented.

**Comment by nirvanatikku** [comment]
I see.. so you don't necessarily want the USD values next to each order.. but you want it for the most recent transactions. Right? I'm trying to avoid confusion.. perhaps I can look at the timestamp of the order and augment the relevant rows. Thoughts?

**Comment by ssithuxz** [comment]
https://i.imgur.com/EEacTB0.png

Something like this
