### ISSUE TITLE
Values in EUR as alternative choice to USD

### ISSUE THREAD

**Issue by abien** [nirvanatikku/bittrex-enhanced#20]
It would be nice to be able to choose an alternative currency to USD.

**Comment by nirvanatikku** [comment]
Makes sense; should extend to all currencies. Thx for creating the issue.

Some questions:
* What would the best source be for BTCEUR? (or generally speaking)
* Thoughts on adding a 3pp to the plugin? I've wanted to minimize as much as possible, for privacy/security reasons.. any feedback would be appreciated.

**Comment by Utone** [comment]
https://bitcoinaverage.com/en/bitcoin-price/btc-to-eur
They take the average price of every mayor exchange. You can set it to any FIAT base currency so would appeal tho the international community.

And i'm sure they provide api or web-sockets to get the prices in real-time, compare them tperhaps even for arbitrage opportunities ;)

Good luck, love to contribute in any way I can..

Thanks for making this

**Comment by ktjbrowne** [comment]
First, yes, thanks for making the plugin, really cool, a great enhancement to Bittrex!
I would also like to see a EUR price option. 
That would be great...
thanks.
K.

**Comment by abien** [comment]
Nevermind this.
