### ISSUE TITLE
Uncaught TypeError: Cannot read property 'innerText' of undefined

### ISSUE THREAD

**Issue by hydex86** [nirvanatikku/bittrex-enhanced#25]
I'm experiencing this issue in Bittrex Wallet section:

```
Uncaught TypeError: Cannot read property 'innerText' of undefined
    at Object.balanceTable [as enhanceBalanceTable] (enhancer.js:245)
    at enhancer.js:381
```
Do you know what could be happening?

**Comment by nirvanatikku** [comment]
Thanks for creating this issue. Just addressed this in https://github.com/nirvanatikku/bittrex-enhanced/commit/539af5bcadb9c279a3af17672c7379eeeb5e5a15. Will be in the next release (1.10).
