### ISSUE TITLE
Make tradingview remember my settings?

### ISSUE THREAD

**Issue by ssithuxz** [nirvanatikku/bittrex-enhanced#4]
Is there anyway for tradingview to remember the indicators that I used before?
Is there a way for me to change the timezone?

Thanks !

**Comment by nirvanatikku** [comment]
Absolutely - although not described yet, this is what https://github.com/nirvanatikku/bittrex-enhanced/issues/1 is for. Working on it now; will be available in 1.6.0. Likely will require you to assign those settings; not 100% sure if its possible to 'remember' what you setup in TV.

**Comment by nirvanatikku** [comment]
@sithulol please check v1.6.0; and lmk if this can be closed out (or if you had something else in mind).

**Comment by ssithuxz** [comment]
you are the best !
